/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.javagui;
import java.sql.ResultSetMetaData;  // Pastikan yang digunakan ini
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;  // Import untuk koneksi MySQL
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
/**
 *
 * @author Kyuusha
 */
public class DaftarBarang extends javax.swing.JFrame {
    Connection Con; 
    ResultSet RsBrg; 
    Statement stm; 
    public FormTransaksiPenjualan fAB = null; 
    private Object[][] dataTable = null; 
    private String[] header = {"Kode","Nama Barang","Satuan","Harga","Harga Beli","Stok","Stok Min"};
    /**
     * Creates new form DaftarBarang
     */
    public DaftarBarang() {
        initComponents();
        tblBrg.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblBrgMouseClicked(evt);
        }
    });
        baca_data();
    }

    DaftarBarang(FormTransaksiPenjualan aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBrg = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DAFTAR BARANG");

        tblBrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Barang", "Satuan", "Harga Jual", "Harga Beli", "Stok", "Stok Minimal"
            }
        ));
        jScrollPane2.setViewportView(tblBrg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void open_db() {
        try {
            // Host, user, pass, db sesuai kebutuhan
            KoneksiMysql kon = new KoneksiMysql("localhost", "root", "", "pos_javagui"); 
            Con = kon.getConnection(); 
        } catch (Exception e) {
            System.out.println("Error : " + e.getMessage()); 
        }
    }

    private void baca_data() {
        open_db();
        try {
            stm = Con.createStatement();
            RsBrg = stm.executeQuery("SELECT * FROM barang ORDER BY kd_brg");

            // simpan sementara di ArrayList
            ArrayList<Object[]> list = new ArrayList<>();
            while (RsBrg.next()) {
                Object[] row = {
                    RsBrg.getString("kd_brg"),
                    RsBrg.getString("nm_brg"),
                    RsBrg.getString("satuan"),
                    RsBrg.getDouble("harga_jual"),
                    RsBrg.getDouble("harga_beli"),
                    RsBrg.getInt("stok"),
                    RsBrg.getInt("stok_min")
                };
                list.add(row);
            }

            // convert ke array 2 dimensi
            Object[][] dataTable = new Object[list.size()][];
            for (int i = 0; i < list.size(); i++) {
                dataTable[i] = list.get(i);
            }

            tblBrg.setModel(new DefaultTableModel(dataTable, header));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


    private void tblBrgMouseClicked(java.awt.event.MouseEvent evt) {                                     
        int row = tblBrg.getSelectedRow();
        if (row >= 0) {
            // ambil data barang sesuai index kolom
            String kode  = tblBrg.getValueAt(row, 0).toString(); // kolom Kd Barang
            String nama  = tblBrg.getValueAt(row, 1).toString(); // kolom Nama Barang
            String harga = tblBrg.getValueAt(row, 3).toString(); // kolom Harga Barang

            // lempar ke form transaksi
            if (fAB != null) {
                fAB.idBrg    = kode;   // simpan ke variabel penampung
                fAB.namaBrg  = nama;
                fAB.hargaBrg = harga;
                fAB.itemTerpilih();    // panggil method di form transaksi
            }

            this.dispose(); // tutup form daftar barang
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBrg;
    // End of variables declaration//GEN-END:variables
}
