/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.javagui;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.sql.ResultSetMetaData;  // Pastikan yang digunakan ini
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;  // Import untuk koneksi MySQL
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import javax.swing.JSpinner;
import javax.swing.SwingWorker;
/**
 *
 * @author Kyuusha
 */
public class FormTransaksiPenjualan extends javax.swing.JFrame {
    Connection Con;
    ResultSet RsBrg;
    ResultSet RsKons;
    Statement stm;
    double total=0;
    String tanggal;
    Boolean edit=false;
    
    // 👉 variabel penampung dari DaftarBarang
    public String idBrg, namaBrg, hargaBrg;

    // method dipanggil setelah pilih barang
    public void itemTerpilih() {
        kd_brg.setSelectedItem(idBrg);
        nm_brg.setText(namaBrg);     // nm_brg = JTextField di form
        hrg_jual.setText(hargaBrg);  // hrg_jual = JTextField di form
    }
    DefaultTableModel tableModel = new DefaultTableModel(
      new Object [][] {},
      new String [] {
        "Kd Barang", "Nama Barang","Harga Barang","Jumlah","Total"
      });

    /**
     * Creates new form FormTransaksiPenjualan
     */
    public FormTransaksiPenjualan() {
        initComponents();
        initTableJual();

    // kosongkan semua input awal
    kosong();
    kosong_detail();
    kd_kons.removeAllItems();
    kd_brg.removeAllItems();

    jml_jual.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            if (!jml_jual.getText().equals("")) {
                try {
                    double harga = Double.parseDouble(hrg_jual.getText());
                    int jml = Integer.parseInt(jml_jual.getText());
                    double total = harga * jml;
                    totjual.setText(Double.toString(total));
                } catch (Exception e) {
                    totjual.setText("0");
                }
            } else {
                totjual.setText("0");
            }
        }
    });

    open_db();
    inisialisasi_tabel();
    aktif(false);
    setTombol(true);
    totjualdetail.setEditable(false);
    kembalian.setEditable(false);
    tgl_jual.setEditor(new JSpinner.DateEditor(tgl_jual, "yyyy/MM/dd"));
    
    // 👉 jangan langsung baca data konsumen & barang
    // baca_konsumen();
    // baca_barang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambah = new javax.swing.JButton();
        kd_brg = new javax.swing.JComboBox<>();
        but_cari = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        cari_brg = new javax.swing.JTextField();
        nm_brg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tgl_jual = new javax.swing.JSpinner();
        cetak = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bayardetail = new javax.swing.JTextField();
        hrg_jual = new javax.swing.JTextField();
        no_jual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        batal = new javax.swing.JButton();
        kembalian = new javax.swing.JTextField();
        jml_jual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        totjual = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        print = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        hapus_item = new javax.swing.JButton();
        kd_kons = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJual = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        totjualdetail = new javax.swing.JTextField();
        nm_kons = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        kd_brg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kd_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kd_brgActionPerformed(evt);
            }
        });

        but_cari.setText("Pilih Barang");
        but_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cariActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        cari_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_brgActionPerformed(evt);
            }
        });

        jLabel1.setText("No. Jual");

        tgl_jual.setModel(new javax.swing.SpinnerDateModel());

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        jLabel2.setText("Tgl. Jual");

        bayardetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayardetailActionPerformed(evt);
            }
        });

        no_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_jualActionPerformed(evt);
            }
        });

        jLabel7.setText("Kembali");

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        jml_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml_jualActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Konsumen");

        totjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totjualActionPerformed(evt);
            }
        });

        print.setColumns(20);
        print.setRows(5);
        jScrollPane2.setViewportView(print);

        jLabel6.setText("Bayar");

        hapus_item.setText("Hapus Item");
        hapus_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_itemActionPerformed(evt);
            }
        });

        kd_kons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kd_konsActionPerformed(evt);
            }
        });

        tblJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kd Barang", "Nama Barang", "Harga Barang", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblJual);

        jLabel4.setText("Nama Konsumen");

        totjualdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totjualdetailActionPerformed(evt);
            }
        });

        nm_kons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_konsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(no_jual)
                            .addComponent(tgl_jual))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nm_kons)
                            .addComponent(kd_kons, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(hapus_item)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(but_cari)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cari_brg))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(kd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(nm_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(hrg_jual, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jml_jual, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(totjual, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(totjualdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bayardetail, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cetak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(batal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(keluar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(no_jual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(kd_kons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tgl_jual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nm_kons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrg_jual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jml_jual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus_item)
                    .addComponent(but_cari)
                    .addComponent(cari_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totjualdetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bayardetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(simpan)
                    .addComponent(cetak)
                    .addComponent(batal)
                    .addComponent(keluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        aktif(true);
        setTombol(false);
        kosong();
        kosong_detail();
        nomor_jual();
        baca_konsumen();
        baca_barang();
        total = 0;
        totjual.setText("0");
    }//GEN-LAST:event_tambahActionPerformed

    private void but_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cariActionPerformed
        DaftarBarang fDB = new DaftarBarang();
        fDB.fAB = this;   // biar bisa lempar balik ke form ini
        fDB.setVisible(true);
        fDB.setResizable(false);
    }//GEN-LAST:event_but_cariActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        simpan_transaksi();
        kosong();
        kosong_detail();
        aktif(false);
        setTombol(true);

        // kosongkan combobox
        kd_kons.removeAllItems();
        kd_brg.removeAllItems();

        // kosongkan tabel
        tableModel.setRowCount(0);

        // reset JTextArea print
        print.setText("");

        // reset total, bayar, kembalian
        totjualdetail.setText("");
        bayardetail.setText("");
        kembalian.setText("");

        // readonly fields tetap readonly
        totjualdetail.setEditable(false);
        kembalian.setEditable(false);

        // fokus ke field awal (opsional)
        kd_kons.requestFocus();
    }//GEN-LAST:event_simpanActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        StringBuilder ctk = new StringBuilder();

    // ===== Header Toko =====
    ctk.append("WARWA - Warung Jawa\n");
    ctk.append("Jl. Jawir No.123, Kota Semarang\n");
    ctk.append("Telp: 0812-XXXX-XXXX\n");
    ctk.append("===========================================\n");
    ctk.append(String.format("Nota Penjualan No: %s%n", no_jual.getText()));
    ctk.append(String.format("Tanggal         : %s%n", tanggal));
    ctk.append("===========================================\n");

    // ===== Daftar Barang =====
    ctk.append(String.format("%-10s %-20s %10s %5s %10s%n", "Kode", "Nama Barang", "Harga", "Jml", "Total"));
    ctk.append("-----------------------------------------------------------------------\n");

    double totalNota = 0;
    for (int i = 0; i < tblJual.getRowCount(); i++) {
        String xkd = (String) tblJual.getValueAt(i, 0);
        String xnama = (String) tblJual.getValueAt(i, 1);
        double xhrg = Double.parseDouble(tblJual.getValueAt(i, 2).toString());
        int xjml = Integer.parseInt(tblJual.getValueAt(i, 3).toString());
        double xtot = Double.parseDouble(tblJual.getValueAt(i, 4).toString());
        totalNota += xtot;

        ctk.append(String.format("%-10s %-20s %10.2f %5d %10.2f%n", xkd, xnama, xhrg, xjml, xtot));
    }

    ctk.append("--------------------------------------------------------------\n");

    // ===== Total, Bayar, Kembalian =====
    ctk.append(String.format("%-35s %10.2f%n", "TOTAL :", totalNota));

    try {
        String bayarStr = bayardetail.getText().trim();
        if (!bayarStr.isEmpty()) {
            double bayarNom = Double.parseDouble(bayarStr);
            double kembalianNom = bayarNom - totalNota;
            ctk.append(String.format("%-35s %10.2f%n", "BAYAR :", bayarNom));
            ctk.append(String.format("%-35s %10.2f%n", "KEMBALIAN :", kembalianNom));
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Input bayar harus angka!");
    }

    // ===== Set ke TextArea =====
    print.setText(ctk.toString());

    // ===== Cetak =====
    MessageFormat header = new MessageFormat("");
    MessageFormat footer = new MessageFormat("");
    boolean interactive = true;
    PrintingTask task = new PrintingTask(header, footer, interactive);
    task.execute();
    }//GEN-LAST:event_cetakActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
    // kosongkan field utama dan detail
        kosong();
        kosong_detail();

        // kosongkan combobox
        kd_kons.removeAllItems();
        kd_brg.removeAllItems();

        // kosongkan tabel
        tableModel.setRowCount(0);

        // reset JTextArea print
        print.setText("");

        // reset total, bayar, kembalian
        totjualdetail.setText("");
        bayardetail.setText("");
        kembalian.setText("");

        // set aktif / nonaktif sesuai awal
        aktif(false);
        setTombol(true);

        // readonly fields tetap readonly
        totjualdetail.setEditable(false);
        kembalian.setEditable(false);

        // fokus ke field awal (opsional)
        kd_kons.requestFocus();
    }//GEN-LAST:event_batalActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void hapus_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_itemActionPerformed
        int row = tblJual.getSelectedRow();
        if (row >= 0) {
            tableModel.removeRow(row);   // Ganti model → tableModel
            hitungTotalTransaksi();      // Re-hit total setelah hapus
        } else {
            JOptionPane.showMessageDialog(this, "Pilih item yang mau dihapus!");
        }
    }//GEN-LAST:event_hapus_itemActionPerformed

    private void kd_konsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kd_konsActionPerformed
        if (kd_kons.getSelectedItem() != null) {
            detail_konsumen(kd_kons.getSelectedItem().toString());
        }
    }//GEN-LAST:event_kd_konsActionPerformed

    private void no_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_jualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_jualActionPerformed

    private void nm_konsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_konsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nm_konsActionPerformed

    private void kd_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kd_brgActionPerformed
        if (kd_brg.getSelectedItem() != null) {
        cari_brg.setText(kd_brg.getSelectedItem().toString()); // isi juga ke textfield
        detail_barang(kd_brg.getSelectedItem().toString());
    }
    }//GEN-LAST:event_kd_brgActionPerformed

    private void jml_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml_jualActionPerformed
        try {
            String kode = kd_brg.getSelectedItem().toString();
            String nama = nm_brg.getText();
            double harga = Double.parseDouble(hrg_jual.getText());
            int jml = Integer.parseInt(jml_jual.getText());
            double total = harga * jml;

            // tambahkan ke JTable
            tableModel.addRow(new Object[]{kode, nama, harga, jml, total});

            // hitung total keseluruhan
            hitungTotalTransaksi();

            // reset input detail
            kosong_detail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Input tidak valid!");
        }
    }//GEN-LAST:event_jml_jualActionPerformed

    private void totjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totjualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totjualActionPerformed

    private void cari_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_brgActionPerformed
        String kode = kd_brg.getSelectedItem().toString();  // sekarang kd_brg bentuknya JTextField

    if (kode.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan kode barang dulu!");
        return;
    }

    detail_barang(kode);  // langsung pakai detail_barang
    }//GEN-LAST:event_cari_brgActionPerformed

    private void totjualdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totjualdetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totjualdetailActionPerformed

    private void bayardetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayardetailActionPerformed
        try {
            double total = Double.parseDouble(totjualdetail.getText());
            double bayar = Double.parseDouble(bayardetail.getText());
            double kembali = bayar - total;
            kembalian.setText(String.valueOf(kembali));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input bayar tidak valid!");
        }
    }//GEN-LAST:event_bayardetailActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    //method buka database
    private void open_db() {
        try {
            KoneksiMysql kon = new KoneksiMysql(); // langsung pakai constructor default
            Con = kon.getConnection();
            stm = Con.createStatement();
            //System.out.println("Koneksi database berhasil");
        } catch (Exception e) {
            System.out.println("Error open_db : " + e.getMessage());
        }
    }

    private void initTableJual() {
        tblJual.setModel(tableModel); 
    }
    
    // hitung jual
    private void hitung_jual() {
        double xtot, xhrg;
        int xjml;
        xhrg = Double.parseDouble(hrg_jual.getText());
        xjml = Integer.parseInt(jml_jual.getText());
        xtot = xhrg * xjml;
        String xtotal = Double.toString(xtot);
        totjual.setText(xtotal);
        total = total + xtot;
        totjual.setText(Double.toString(total));
    }
    
    private void hitungTotalTransaksi() {
        double total = 0;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            total += Double.parseDouble(tableModel.getValueAt(i, 4).toString()); // kolom total
        }
        totjual.setText(Double.toString(total));
        hitungTotal();
    }

    private void hitungTotal() {
    double total = 0;
    for (int i = 0; i < tableModel.getRowCount(); i++) {
        double harga = Double.parseDouble(tableModel.getValueAt(i, 2).toString());
        int jumlah = Integer.parseInt(tableModel.getValueAt(i, 3).toString());
        total += (harga * jumlah);
    }
    totjualdetail.setText(String.valueOf(total));
}
    
    private void baca_konsumen() {
        try {
            stm = Con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT kd_kons, nm_kons FROM konsumen");
            kd_kons.removeAllItems();
            while(rs.next()) {
                kd_kons.addItem(rs.getString("kd_kons"));
            }
            rs.close();
        } catch(SQLException e) {
            System.out.println("Error baca_konsumen : " + e.getMessage());
        }
    }

    private void baca_barang() {
        try {
            stm = Con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT kd_brg, nm_brg FROM barang");
            kd_brg.removeAllItems();
            while(rs.next()) {
                kd_brg.addItem(rs.getString("kd_brg"));
            }
            rs.close();
        } catch(SQLException e) {
            System.out.println("Error baca_barang : " + e.getMessage());
        }
    }
    
    private void detail_konsumen(String xkode) {
        try {
            stm = Con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT * FROM konsumen WHERE kd_kons='"+xkode+"'");
            if(rs.next()) {
                nm_kons.setText(rs.getString("nm_kons"));
            }
            rs.close();
        } catch(SQLException e) {
            System.out.println("Error detail_konsumen : " + e.getMessage());
        }
    }
    
    private void detail_barang(String xkode) {
        try {
            Statement stmt = Con.createStatement();
            String sql = "SELECT kd_brg, nm_brg, harga_jual FROM barang WHERE kd_brg='" + xkode + "'";
            ResultSet rs = stmt.executeQuery(sql);

            if (rs.next()) {
                kd_brg.setSelectedItem(rs.getString("kd_brg")); // set combobox / textfield
                nm_brg.setText(rs.getString("nm_brg"));
                hrg_jual.setText(String.valueOf(rs.getDouble("harga_jual")));
            } else {
                nm_brg.setText("");
                hrg_jual.setText("");
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            System.out.println("Error detail_barang : " + e.getMessage());
        }
    }

    // set model tabel
    public void inisialisasi_tabel() {
        tblJual.setModel(tableModel);
    }

    // kosongkan isian utama
    private void kosong() {
        no_jual.setText("");
        nm_kons.setText("");
        hrg_jual.setText("");
        totjual.setText("");
    }

    // kosongkan detail barang
    private void kosong_detail() {
        nm_brg.setText("");
        hrg_jual.setText("");
        jml_jual.setText("");
        totjual.setText("");
    }

    // aktif / nonaktif input
    private void aktif(boolean x) {
        kd_kons.setEnabled(x);
        kd_brg.setEnabled(x);
        tgl_jual.setEnabled(x);
        jml_jual.setEditable(x);
    }

    // set tombol
    private void setTombol(boolean t) {
        tambah.setEnabled(t);
        simpan.setEnabled(!t);
        batal.setEnabled(!t);
        keluar.setEnabled(t);
        hapus_item.setEnabled(!t);
    }

    // nomor jual otomatis
    private void nomor_jual() {
        try {
            stm = Con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT no_jual FROM jual");
            int brs = 0;
            while (rs.next()) {
                brs = rs.getRow();
            }
            if (brs == 0) {
                no_jual.setText("1");
            } else {
                int nom = brs + 1;
                no_jual.setText(Integer.toString(nom));
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println("Error nomor_jual : " + e.getMessage());
        }
    }

    // simpan transaksi
    private void simpan_transaksi() {
    try {
        String xnojual = no_jual.getText();
        format_tanggal();
        String xkode = kd_kons.getSelectedItem().toString();

        // simpan ke tabel jual
        String msql = "INSERT INTO jual VALUES('" + xnojual + "','" + xkode + "','" + tanggal + "')";
        stm.executeUpdate(msql);

        // simpan ke tabel detail (djual)
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String xkd = (String) tableModel.getValueAt(i, 0); // kd_brg
            double xhrg = Double.parseDouble(tableModel.getValueAt(i, 2).toString());
            int xjml = Integer.parseInt(tableModel.getValueAt(i, 3).toString());

            // simpan detail jual
            String zsql = "INSERT INTO djual VALUES('" + xnojual + "','" + xkd + "'," + xhrg + "," + xjml + ")";
            stm.executeUpdate(zsql);

            // update stok barang
            String usql = "UPDATE barang SET stok = stok - " + xjml + " WHERE kd_brg = '" + xkd + "'";
            stm.executeUpdate(usql);
        }

        JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error simpan_transaksi : " + e.getMessage());
    }
}


    // format tanggal
    private void format_tanggal() {
        String DATE_FORMAT = "yyyy-MM-dd";
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat(DATE_FORMAT);
        Calendar c1 = Calendar.getInstance();
        int year = c1.get(Calendar.YEAR);
        int month = c1.get(Calendar.MONTH) + 1;
        int day = c1.get(Calendar.DAY_OF_MONTH);
        tanggal = year + "-" + month + "-" + day;
    }
    
    // Inner class untuk printing
private class PrintingTask extends SwingWorker<Object, Object> { 
    private final MessageFormat headerFormat; 
    private final MessageFormat footerFormat; 
    private final boolean interactive; 
    private volatile boolean complete = false; 
    private volatile String message; 

    public PrintingTask(MessageFormat header, MessageFormat footer, boolean interactive) { 
        this.headerFormat = header; 
        this.footerFormat = footer; 
        this.interactive = interactive; 
    } 

    @Override 
    protected Object doInBackground() { 
        try { 
            complete = print.print(headerFormat, footerFormat, true, null, null, interactive); 
            message = "Printing " + (complete ? "complete" : "canceled"); 
        } catch (PrinterException ex) { 
            message = "Sorry, a printer error occurred"; 
        } catch (SecurityException ex) { 
            message = "Sorry, cannot access the printer due to security reasons"; 
        } 
        return null; 
    } 

    @Override 
    protected void done() { 
        JOptionPane.showMessageDialog(FormTransaksiPenjualan.this, message); 
    } 
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksiPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JTextField bayardetail;
    private javax.swing.JButton but_cari;
    private javax.swing.JTextField cari_brg;
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapus_item;
    private javax.swing.JTextField hrg_jual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jml_jual;
    private javax.swing.JComboBox<String> kd_brg;
    private javax.swing.JComboBox<String> kd_kons;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField nm_brg;
    private javax.swing.JTextField nm_kons;
    private javax.swing.JTextField no_jual;
    private javax.swing.JTextArea print;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tblJual;
    private javax.swing.JSpinner tgl_jual;
    private javax.swing.JTextField totjual;
    private javax.swing.JTextField totjualdetail;
    // End of variables declaration//GEN-END:variables
}
